version: '3.8'

services:
  nest-ionic-todo:
    image: troyhd/nest-ionic-todo:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - todo-data:/app/data

volumes:
  todo-data: